# Generated by Django 2.2.12 on 2020-06-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poste_player', to='myteam.Poste'),
        ),
    ]
