# Generated by Django 2.2.12 on 2020-06-08 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0002_auto_20200608_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='team',
            name='ligue',
        ),
        migrations.AddField(
            model_name='team',
            name='ligue',
            field=models.ManyToManyField(related_name='ligues', to='myteam.Ligue'),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
