# Generated by Django 2.2.12 on 2020-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0002_player_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
