# Generated by Django 2.2.12 on 2020-06-08 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0003_auto_20200608_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='ligue',
        ),
        migrations.AddField(
            model_name='team',
            name='ligue',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='team_ligue', to='myteam.Ligue'),
            preserve_default=False,
        ),
    ]
