# Generated by Django 2.2.13 on 2020-06-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0004_galerieimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myteam/gallery/photo')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SlideImage',
                'verbose_name_plural': 'SlideImages',
            },
        ),
    ]
